### ISSUE TITLE
fire trucks and prison helicopter errors

### ISSUE THREAD

**Issue by t1a2l** [MacSergey/BuildingSpawnPoints#26]
Vehicle not found!
   at System.Environment.get_StackTrace()
   at Building.RemoveOwnVehicle(UInt16 vehicleID, Vehicle ByRef data)
   at FireTruckAI.RemoveSource(UInt16 vehicleID, Vehicle ByRef data)
   at FireTruckAI.ArriveAtSource(UInt16 vehicleID, Vehicle ByRef data)
   at FireTruckAI.ArriveAtDestination(UInt16 vehicleID, Vehicle ByRef vehicleData)
   at CarAI.CarAI.SimulationStep_Patch0(.CarAI , UInt16 , Vehicle ByRef , Frame ByRef , UInt16 , Vehicle ByRef , Int32 )
   at FireTruckAI.FireTruckAI.SimulationStep_Patch1(.FireTruckAI , UInt16 , Vehicle ByRef , Frame ByRef , UInt16 , Vehicle ByRef , Int32 )
   at VehicleAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at TrafficManager.Patch._VehicleAI._CarAI.SimulationStepPatch.Prefix(.CarAI __instance, UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at CarAI.CarAI.SimulationStep_Patch1(.CarAI , UInt16 , Vehicle ByRef , Vector3 )
   at FireTruckAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at VehicleManager.VehicleManager.SimulationStepImpl_Patch0(.VehicleManager , Int32 )
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at VehicleManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]

Vehicle not found!
   at System.Environment.get_StackTrace()
   at Building.RemoveGuestVehicle(UInt16 vehicleID, Vehicle ByRef data)
   at PrisonHelicopter.AI.PrisonHelicopterAI.RemoveTarget(UInt16 vehicleID, Vehicle ByRef data)
   at PrisonHelicopter.AI.PrisonHelicopterAI.SetTarget(UInt16 vehicleID, Vehicle ByRef data, UInt16 targetBuilding)
   at PrisonHelicopter.AI.PrisonHelicopterAI.ArriveAtTarget(UInt16 vehicleID, Vehicle ByRef data)
   at PrisonHelicopter.AI.PrisonHelicopterAI.ArriveAtDestination(UInt16 vehicleID, Vehicle ByRef vehicleData)
   at HelicopterAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, Frame ByRef frameData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at HelicopterAI.OpenInstanceDelegate_SimulationStep(.HelicopterAI , UInt16 , Vehicle ByRef , Frame ByRef , UInt16 , Vehicle ByRef , Int32 )
   at PrisonHelicopter.HarmonyPatches.PoliceCopterAIPatch.SimulationStep(.PoliceCopterAI __instance, UInt16 vehicleID, Vehicle ByRef vehicleData, Frame ByRef frameData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at PoliceCopterAI.PoliceCopterAI.SimulationStep_Patch1(.PoliceCopterAI , UInt16 , Vehicle ByRef , Frame ByRef , UInt16 , Vehicle ByRef , Int32 )
   at PrisonHelicopter.AI.PrisonHelicopterAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, Frame ByRef frameData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at VehicleAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at HelicopterAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at PoliceCopterAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at PrisonHelicopter.AI.PrisonHelicopterAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at VehicleManager.VehicleManager.SimulationStepImpl_Patch0(.VehicleManager , Int32 )
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at VehicleManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]

**Comment by t1a2l** [comment]
@MacSergey

**Comment by GIS-PuppetMaster** [comment]
same problem here
