### ISSUE TITLE
Some 'invisible spawn point' buildings are unselectable

### ISSUE THREAD

**Issue by aubergine10** [MacSergey/BuildingSpawnPoints#28]
I'm using the [Invisible 1x1 Spawn Point Variety Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=1361591068) from Steam workshop, and most of the buildings work fine; spawn points can be edited.

However, I've noticed that for Fire Truck and Disaster Vehicle (both the road variants), the buildings cannot be selected for editing.

The buildings highlight when mouse hovers over them, but clicking them has no effect:

![image](https://user-images.githubusercontent.com/1386719/146459574-1f672fc9-89ce-4d03-a732-702f1e129151.png)

Also, if I select the building and click the spawn points button in the building info panel title bar, it activates the spawn points mod but with no building selected:

![image](https://user-images.githubusercontent.com/1386719/146459652-9a0c815b-ebcf-4c3c-8f65-01000c4b242a.png)

![image](https://user-images.githubusercontent.com/1386719/146459671-04fad40b-76ac-46d1-97a1-50511a1dfae8.png)

Again, from this mode, the building will highlight when hovered, but clicking has no effect.

Output log attached:
[output_log.zip](https://github.com/MacSergey/BuildingSpawnPoints/files/7730827/output_log.zip)

There's a load of exceptions at the end of the log, for example:

```
[BuildingSpawnPoints] Enable tool
NullReferenceException: Object reference not set to an instance of an object
  at BuildingSpawnPoints.AIExtension+<GetCopterPoints>d__28.MoveNext () [0x00000] in <filename unknown>:0 
  at BuildingSpawnPoints.BuildingData.ResetToDefault () [0x00000] in <filename unknown>:0 
  at BuildingSpawnPoints.BuildingData..ctor (UInt16 id, Boolean init) [0x00000] in <filename unknown>:0 
  at BuildingSpawnPoints.Manager.get_Item (UInt16 id, Options options) [0x00000] in <filename unknown>:0 
  at BuildingSpawnPoints.Patcher+<>c.<BuildingWorldInfoPanelStartPostfix>b__25_1 (ColossalFramework.UI.UIComponent _, ColossalFramework.UI.UIMouseEventParameter _) [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIComponent.OnClick (ColossalFramework.UI.UIMouseEventParameter p) [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIButton.OnClick (ColossalFramework.UI.UIMouseEventParameter p) [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIInput+MouseHandler.ProcessInput (IInputTranslator translator, Ray ray, ColossalFramework.UI.UIComponent component, Boolean retainFocusSetting) [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIInput.ProcessMouseInput () [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIInput.FpsBoosterUpdate () [0x00000] in <filename unknown>:0 
  at BehaviourUpdater.UiInputUpdater.UpdateInput () [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
BehaviourUpdater.UiInputUpdater:UpdateInput()
BehaviourUpdater.Updater:Update()
```

and

```
[BuildingSpawnPoints] Disable tool
Vehicle not found!
   at System.Environment.get_StackTrace()
   at Building.RemoveOwnVehicle(UInt16 vehicleID, Vehicle ByRef data)
   at FireTruckAI.RemoveSource(UInt16 vehicleID, Vehicle ByRef data)
   at FireTruckAI.ArriveAtSource(UInt16 vehicleID, Vehicle ByRef data)
   at FireTruckAI.ArriveAtDestination(UInt16 vehicleID, Vehicle ByRef vehicleData)
   at CarAI.CarAI.SimulationStep_Patch0(.CarAI , UInt16 , Vehicle ByRef , Frame ByRef , UInt16 , Vehicle ByRef , Int32 )
   at FireTruckAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, Frame ByRef frameData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at VehicleAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at TrafficManager.Patch._VehicleAI._CarAI.SimulationStepPatch.Prefix(.CarAI __instance, UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at CarAI.CarAI.SimulationStep_Patch1(.CarAI , UInt16 , Vehicle ByRef , Vector3 )
   at FireTruckAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at VehicleManager.SimulationStepImpl(Int32 subStep)
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at VehicleManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]
```

etc.

**Comment by aubergine10** [comment]
Customize It: Extended settings for the fire engine spawn:

![image](https://user-images.githubusercontent.com/1386719/146462693-83144052-c01e-4e46-a0fd-9c649cead32a.png)

and the Disaster veh spawn:

![image](https://user-images.githubusercontent.com/1386719/146462765-60202a65-f38e-46d6-a56e-5f9d7fa33915.png)

**Comment by aubergine10** [comment]
BTW, these spawn points used to be editable with the Building Spawn Points mod - so maybe it's a mod I've recently started using?

Following mods recently subscribed:

* [RON](https://steamcommunity.com/sharedfiles/filedetails/?id=2405917899)
* [BOB](https://steamcommunity.com/sharedfiles/filedetails/?id=2197863850)
* [Curb Height Adjuster](https://steamcommunity.com/sharedfiles/filedetails/?id=2674842365)
